### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by SillyInventor** [CSnap/rpi_csdt_community#107]
I didn't turn off my notifications for drone.io and got notified of a failure:
https://drone.io/github.com/CSnap/rpi_csdt_community/28

Looks like some conflict between Treebeard and Django 1.10:
```
python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/virtualenv/python2.7/local/lib/python2.7/site-packages/treebeard/admin.py", line 6, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns
```

**Comment by chuck211991** [comment]
I encountered that issue on my desktop; I fixed it by pulling treebeard from a repository that had fixed it (they have had a pull request in for a few weeks, but no one upstream has taken it).

See [this](https://github.com/CSnap/rpi_csdt_community/pull/106) commit and [this](https://github.com/CSnap/rpi_csdt_community/pull/106/files#diff-bd45bc69eea3ed855075429a1b42e2d5) file. Can you add me to the email recipient for that build?

**Comment by SillyInventor** [comment]
Nice and fast catch. I have added you to the drone.io notifications.

Consider doing a CSnap fork of basic treebeard, making the 2-3 changes to URL patterns required, submitting a pull request, and using ours in the interim. Previous such repositories have been deleted and have had to be replaced.

**Comment by SillyInventor** [comment]
The failure has changed, but still there. The problem seems to be that easy_thumbnails needs to be added to the installed apps.

**Comment by chuck211991** [comment]
As of this evening, the build is passing. Heroku deployment wasn't working, but since no one uses it, I just disabled it.

https://drone.io/github.com/GK-12/rpi_csdt_community/160
